apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
  # namespace: {{ default "staging" .Release.Namespace }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: imagestorage
    volumeAttributes:
      shareName: imagestorage
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
      #namespace: {{ default "staging" .Release.Namespace }}
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
