apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: azurefile-{{ default "staging" .Release.Namespace }}
  resources:
    requests:
      storage: 1Gi
