apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ default "staging" .Release.Namespace }}
  name: my-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-azurefile
  resources:
    requests:
      storage: 124Mi
