apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
      name: python-app
  selector:
    app: python-app
  type: ClusterIP
