name: Build and push the latest build to prodaction

on:
  push:
    tags:
      - 'v*'

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Fetch latest version
        id: fetch_version
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.ACR_NAME }} 
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push staging images
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          push: true
          tags: ${{secrets.ACR_NAME}}/${{ secrets.IMAGE }}:latest,${{secrets.ACR_NAME}}/${{ secrets.IMAGE }}:${{ steps.fetch_version.outputs.TAG }}
 
  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image

    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: v3.3.1

      - name: Get AKS Credentials
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.RESOURCE_GROUP }} 
          cluster-name: ${{ secrets.CLUSTER_NAME }}

      #- name: Remove old Kubernetes secret
      #  run: |
      #    kubectl delete secret azure-secret \
      #    -n production

      #- name: Create Kubernetes secret
      #  run: |
      #    kubectl create secret generic azure-secret \
      #    --from-literal=azurestorageaccountname=${{ secrets.STORAGE_ACCOUNT_NAME }} \
      #    --from-literal=azurestorageaccountkey=${{ secrets.STORAGE_KEY }} \
      #    -n production

      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --namespace production \
            python-app \
            ./kubernetes/python-app \
            --set replicas=3 \
            --set image.repository=${{ secrets.ACR_NAME }} \
            --set dns.name=${{ secrets.DNS_NAME }} \
            --set image.tag=${GITHUB_REF#refs/tags/}
